# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
        cache: 'npm'
      env:
        SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
    - name: Check yarn.lock
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "yarn.locks"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      # Only runs if all of the files exists
      run: exit 1
    - run: echo $SHOPIFY_DOMAIN
    - run: exit 1
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
